### ISSUE TITLE
Reduce image size?

### ISSUE THREAD

**Issue by abettermap** [php-earth/docker-pandoc#1]
My own `pandoc` attempts with Docker were not successful when converting `docx` to `html`, but your image worked just fine. Nicely done! Just one small request (or rather a question since I can make the tweaks myself):

**How can I reduce the image size?**

The current one is rather large at `1.43GB`:

```bash
$ docker images | grep phpearth
phpearth/pandoc        latest       ac9e5368509c        11 days ago         1.43GB
```

We will be using this in CI and would like to slim it down a bit, and since we will only be going from `docx` to `html` I was wondering if I could remove some of the `apt-get` packages and still preserve the same functionality? None of them look familiar to me (except `wget`) so I am reluctant to remove any, but please let me know if that is possible for the conversion between the two file types I mentioned.

Thanks in advance, and if you want anything edited in the README for other users looking for smaller images, please let me know and I can submit a PR.

**Comment by petk** [comment]
Hello @abettermap

Sorry for missing this issue and not taking a look at it sooner. I've been too busy.

The other packages in the Docker image are mostly concerning fonts for some of the contents out there so they build properly. Otherwise, image can be greatly reduced if the `texlive-fonts-extra` and some others are removed from it.

You're welcome to suggest changes to the README file if you're still interested.

Otherwise, I've moved this image from phpearth to petk namespace in the meantime. Cheers.
